#!/bin/bash

BW_MEM_THREADS="1 2 3 4"
BW_MEM_SIZES="16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072"

LAT_MEM_RD_SIZE=128
LAT_MEM_RD_STRIDES="16 32 64 128 256 512"

# Get the time
cat /proc/uptime
uptime

for THREADS in $BW_MEM_THREADS; do
        echo
        echo "memory read bandwidth ($THREADS threads) [segment size in MByte vs bandwidth in MByte/s]"
        for SIZE in $BW_MEM_SIZES; do
                echo "bw_mem -N 1 -P $THREADS ${SIZE}k rd"
		/usr/bin/time bw_mem -N 1 -P $THREADS ${SIZE}k rd 2> /dev/console
        done

        echo
        echo "memory write bandwidth ($THREADS threads) [segment size in MByte vs bandwidth in MByte/s]"
        for SIZE in $BW_MEM_SIZES; do
                echo "bw_mem -N 1 -P $THREADS ${SIZE}k wr"
                /usr/bin/time bw_mem -N 1 -P $THREADS ${SIZE}k wr 2> /dev/console
        done
	echo
done

# Get the time
uptime
cat /proc/uptime
